SS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('SmartServices.urls')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

SmartServices/urls.py
from typing import Pattern
from django.contrib import admin
from django.urls import path
from . import views

app_name = "SmartServices"


urlpatterns = [
    path('',views.home,name= "home"),
    path('base/',views.partnerhome,name= "base"),
    path('About/',views.Aboutus,name= "about"),
    path('Contact/',views.Contact,name= "contact"),
 
    path('Email/',views.SuccesEmail,name= "email"),
    path('register/', views.register, name="register"),
    path('login/',views.loginpage, name= "login"),
    path('logout/',views.logoutUser, name= "logout"),

    path('HirePage/',views.HirePage, name= "HirePage"),

    path(r'form/',views.CreatePatner, name= "form"),
    # path(r'form/',views.FinalPlaceOrder, name= "form2"),

    path(r'worker/<slug:slug>/',views.worker_details, name= "worker_details"),

    path('search/<slug:category_slug>/', views.category_list, name= "category_list"),
]

SmartServices/models.py
from datetime import timezone
from email.policy import default
from turtle import mode
from django.db import models
from django.db import models
from django.db.models.expressions import F
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User

class Category(models.Model):
    Name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('SmartServices:category_list', args=[self.slug])

    def __str__(self):
        return self.Name


class Partners(models.Model):
    category = models.ForeignKey(
        Category, related_name='partner', on_delete=models.CASCADE)
    # created_by = models.ForeignKey(
    #     settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='Partner_maker',default='Admin')
    
    Name = models.CharField(max_length=255)
    Address = models.CharField(max_length=255, default='Sangli')
    Contact = models.CharField(max_length=15, null=False, unique=True)
    Alternate_Contact = models.CharField(max_length=15, null=False, unique=True)

    image = models.ImageField(upload_to='images/', default='images/SSDefault.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    OtherExpertise = models.CharField(max_length=255, default="None")

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'partner'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse("SmartServices:worker_details", args=[self.slug])

    def __str__(self):
        return self.Name

class Order(models.Model):
    Name = models.CharField(max_length=250)
    Email = models.EmailField(max_length=255)
    Phone = models.IntegerField()
    Address = models.CharField(max_length=250)                      
    Date = models.DateTimeField(auto_now_add=True)
    Ammount = models.CharField(max_length=100) 
    WokerName = models.CharField(max_length=555)
    
    class Meta:
        verbose_name_plural = 'Order'
    
    def __str__(self):
        return self.Name

SmartServices/forms.py
from django.db.models import fields
from django.db.models.base import Model
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name','last_name' ,'email', 'username','password1', 'password2']

class AddPartner(ModelForm):
    class Meta:
        model = Partners
        fields = '__all__'
        # exclude = ['user']


class PlaceOrder(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        # exclude = ['user']
        

SmartServices/views.py
import email
import imp
from re import U
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string




# Create your views here.
from .models import Order, Partners, Category
from .forms import CreateUserForm, AddPartner, PlaceOrder


# @login_required(login_url='SmartServices:login')
def home(request):
    workers = Partners.objects.all().count()
    Countuser = User.objects.all().count()
    OrderCount = Order.objects.all().count()
    context = {
         'partners': workers,
         'Countuser':Countuser,
         'Ordercount':OrderCount
    }
    return render(request, 'HeaderBase.html',context)

    # return render(request, 'Home.html')


@login_required(login_url='SmartServices:login')
def HirePage(request):
    return render(request, 'MainPages/Categories.html')


def categories(request):
    return {
        'categories': Category.objects.all()
    }

@login_required(login_url='SmartServices:login')
def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    partners = Partners.objects.filter(category=category)
    return render(request, 'MainPages/Hire_Emp.html', {'Category': category, 'partner': partners})

@login_required(login_url='SmartServices:login')
def worker_details(request, slug):
    if request.method == "POST":
        Name = request.POST['name']
        Email = request.POST['email']
        Phone = request.POST['phone']
        Address = request.POST['address']
        Ammount = request.POST['ammount']
        WorkerName = request.POST['workername']

        PlaceOrder = Order(Name = Name, Email = Email, Phone = Phone, Address = Address, Ammount = Ammount, WokerName = WorkerName)
        PlaceOrder.save()
        print(WorkerName)

        return redirect('SmartServices:email')

    worker = get_object_or_404(Partners, slug=slug)
    return render(request, 'MainPages/Single_Detail.html', {'workers': worker})



def BuyPageworker(request, slug):
    worker = get_object_or_404(Partners, slug=slug)
    return render(request, 'MainPages/BuyPage.html', {'workers': worker})

def partnerhome(request):
    return render(request, 'Base.html')


def Aboutus(request):
    return render(request,'PartnerPage/Aboutus.html' )


def Contact(request):
    return render(request,'PartnerPage/Contactus.html' )




# Adding Data into patner model.
def CreatePatner(request):
    if request.method == 'POST':
        form = AddPartner(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('Name')
            messages.success(request, "Welcome To Smart Services  " + user)
         
            return redirect('SmartServices:base')
    else:
        form = AddPartner()
    return render(request, 'MainPages/AddingPartner.html', {'form': form})



## Sending Email 

def SuccesEmail(request):
    import datetime
    NextDay_Date = datetime.datetime.today() + datetime.timedelta(days=2)
    Day = NextDay_Date.day 
    Month = NextDay_Date.month 
    Y = NextDay_Date.year 
       
    tenplate = render_to_string('Email_Pop/EmailTmp.html',{'name':request.user})
    email = EmailMessage(
        ['SMART_SERVICES',Day,Month,Y],
        tenplate,
        settings.EMAIL_HOST_USER,
        [request.user.email],
    )
    email.fail_silently = False
    email.send(NextDay_Date)
    return render(request,'Email_Pop/Pop.html')







def register(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, "Acoount Created " + user)

                return redirect('SmartServices:login')

        context = {'form': form}
        return render(request, 'AccountData/Register.html', context)


def loginpage(request):
    if request.user.is_authenticated:
        return redirect('/')

    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/')

            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'AccountData/Login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('SmartServices:login')

SmartServices/templates/AccountData/Login.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: linear-gradient(135deg, #d1a74d, #a038c9);
            font-family: 'Poppins', sans-serif;
        }


        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #ffffff;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: rgb(0, 0, 0);
            font-family:"Lucida" Grande, sans-serif;

        }

        .login_btn {
            width: 100%;
            background: linear-gradient(135deg, #d1a74d, #a038c9);
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
    </style>

</head>

<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">


                    <h3 id="form-title"> Login </h3>
                </div>
                <div class="d-flex justify-content-center form_container">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>

                            <input type="text" name="username" placeholder="Username..." class="form-control">
                        </div>

                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>

                            <input type="password" name="password" placeholder="Password..." class="form-control">
                        </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <input class="btn login_btn" type="submit" value="Login">
                        </div>
                    </form>

                </div>

                {% for message in messages %}
                <p id="messages">{{message}}</p>
                {% endfor %}

                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Dont have an account? <a href="{% url 'SmartServices:register' %}" class="ml-2">Register</a>
        
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</body>

</html>

SmartServices/templates/AccountData/Register.html
<!DOCTYPE html>

<html lang="en" dir="ltr">

<head>
  <meta charset="UTF-8">
  <!---<title> Responsive Registration Form | CodingLab </title>-->
  <link rel="stylesheet" href="style.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');

  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
  }

  body {
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 10px;
    background: linear-gradient(135deg, #d1a74d, #a038c9);
  }

  .container {
    max-width: 700px;
    width: 100%;
    background-color: #fff;
    padding: 25px 30px;
    border-radius: 5px;
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.15);
  }

  .container .title {
    font-size: 25px;
    font-weight: 500;
    position: relative;
  }

  
  .container .title::before {
    content: "";
    position: absolute;
    left: 0;
    bottom: 0;
    height: 3px;
    width: 30px;
    border-radius: 5px;
    background: linear-gradient(135deg, #71b7e6, #9b59b6);
  }

  .content form .user-details {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    margin: 20px 0 12px 0;
  }

  form .user-details .input-box {
    margin-bottom: 15px;
    width: calc(100% / 2 - 20px);
  }

  form .input-box span.details {
    display: block;
    font-weight: 500;
    margin-bottom: 5px;
  }

  .user-details .input-box input {
    height: 45px;
    width: 100%;
    outline: none;
    font-size: 16px;
    border-radius: 5px;
    padding-left: 15px;
    border: 1px solid #ccc;
    border-bottom-width: 2px;
    transition: all 0.3s ease;
  }

  .user-details .input-box input:focus,
  .user-details .input-box input:valid {
    border-color: #9b59b6;
  }

  form .gender-details .gender-title {
    font-size: 20px;
    font-weight: 500;
  }

  form .category {
    display: flex;
    width: 80%;
    margin: 14px 0;
    justify-content: space-between;
  }

  form .category label {
    display: flex;
    align-items: center;
    cursor: pointer;
  }

  form .category label .dot {
    height: 18px;
    width: 18px;
    border-radius: 50%;
    margin-right: 10px;
    background: #d9d9d9;
    border: 5px solid transparent;
    transition: all 0.3s ease;
  }

  #dot-1:checked~.category label .one,
  #dot-2:checked~.category label .two,
  #dot-3:checked~.category label .three {
    background: #c48e47;
    border-color: #d9d9d9;
  }

  form input[type="radio"] {
    display: none;
  }

  form .button {
    height: 45px;
    margin: 35px 0
  }

  form .button input {
    height: 100%;
    width: 100%;
    border-radius: 5px;
    border: none;
    color: #fff;
    font-size: 18px;
    font-weight: 500;
    letter-spacing: 1px;
    cursor: pointer;
    transition: all 0.3s ease;
    background: linear-gradient(135deg, #71b7e6, #9b59b6);
  }

  form .button input:hover {
    /* transform: scale(0.99); */
    background: linear-gradient(-135deg, #71b7e6, #43c97a);
  }

  @media(max-width: 584px) {
    .container {
      max-width: 100%;
    }

    form .user-details .input-box {
      margin-bottom: 15px;
      width: 100%;
    }

    form .category {
      width: 100%;
    }

    .content form .user-details {
      max-height: 300px;
      overflow-y: scroll;
    }

    .user-details::-webkit-scrollbar {
      width: 5px;
    }
  }

  @media(max-width: 459px) {
    .container .content .category {
      flex-direction: column;
    }
  }
</style>

<body>
  <div class="container">
    <div class="title">Registration</div>
    <div class="content">
        <form method="POST" action="">
            {% csrf_token %}
        <div class="user-details">
          <div class="input-box">
            <span class="details">First Name</span>
            {{ form.first_name}}
          </div>
          <div class="input-box">
            <span class="details">Last Name</span>
            {{ form.last_name}}
          </div>


          <div class="input-box">
            <span class="details">Email</span>
            {{ form.email}}
          </div>


          <div class="input-box">
            <span class="details">UserName</span>
            {{ form.username}}
          </div>

          <div class="input-box">
            <span class="details">Password</span>
            {{ form.password1}}
          </div>
          <div class="input-box">
            <span class="details">Confirm Password</span>
            {{ form.password2}}
          </div>
        </div>
        
        <div class="button">
          <input type="submit" value="Register">
        </div>

        <div class="mt-4">
          <div class="d-flex justify-content-center links">
              Already have an account? <a href="{% url 'SmartServices:login' %}" class="ml-2">Login</a>

          </div>


        {{form.errors}}
    </div>
  </div>
  <script>
    
    /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field 
*/

//Query All input fields
var form_fields = document.getElementsByTagName('input')
form_fields[1].placeholder='FirstName..';
form_fields[2].placeholder='LastName..';
form_fields[3].placeholder='Email..';
form_fields[4].placeholder='UserName';
form_fields[5].placeholder='Enter Password...';
form_fields[6].placeholder='Re-Enter Password...';


for (var field in form_fields){	
form_fields[field].className += ' form-control'
}
</script>

</body>

</html>