SS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('SmartServices.urls')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

SmartServices/urls.py
from typing import Pattern
from django.contrib import admin
from django.urls import path
from . import views

app_name = "SmartServices"


urlpatterns = [
    path('',views.home,name= "home"),
    path('base/',views.partnerhome,name= "base"),
    path('About/',views.Aboutus,name= "about"),
    path('Contact/',views.Contact,name= "contact"),
 
    path('Email/',views.SuccesEmail,name= "email"),
    path('register/', views.register, name="register"),
    path('login/',views.loginpage, name= "login"),
    path('logout/',views.logoutUser, name= "logout"),

    path('HirePage/',views.HirePage, name= "HirePage"),

    path(r'form/',views.CreatePatner, name= "form"),
    # path(r'form/',views.FinalPlaceOrder, name= "form2"),

    path(r'worker/<slug:slug>/',views.worker_details, name= "worker_details"),

    path('search/<slug:category_slug>/', views.category_list, name= "category_list"),
]

SmartServices/models.py
from datetime import timezone
from email.policy import default
from turtle import mode
from django.db import models
from django.db import models
from django.db.models.expressions import F
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User

class Category(models.Model):
    Name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('SmartServices:category_list', args=[self.slug])

    def __str__(self):
        return self.Name


class Partners(models.Model):
    category = models.ForeignKey(
        Category, related_name='partner', on_delete=models.CASCADE)
    # created_by = models.ForeignKey(
    #     settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='Partner_maker',default='Admin')
    
    Name = models.CharField(max_length=255)
    Address = models.CharField(max_length=255, default='Sangli')
    Contact = models.CharField(max_length=15, null=False, unique=True)
    Alternate_Contact = models.CharField(max_length=15, null=False, unique=True)

    image = models.ImageField(upload_to='images/', default='images/SSDefault.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    OtherExpertise = models.CharField(max_length=255, default="None")

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'partner'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse("SmartServices:worker_details", args=[self.slug])

    def __str__(self):
        return self.Name

class Order(models.Model):
    Name = models.CharField(max_length=250)
    Email = models.EmailField(max_length=255)
    Phone = models.IntegerField()
    Address = models.CharField(max_length=250)                      
    Date = models.DateTimeField(auto_now_add=True)
    Ammount = models.CharField(max_length=100) 
    WokerName = models.CharField(max_length=555)
    
    class Meta:
        verbose_name_plural = 'Order'
    
    def __str__(self):
        return self.Name

SmartServices/forms.py
from django.db.models import fields
from django.db.models.base import Model
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name','last_name' ,'email', 'username','password1', 'password2']

class AddPartner(ModelForm):
    class Meta:
        model = Partners
        fields = '__all__'
        # exclude = ['user']


class PlaceOrder(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        # exclude = ['user']
        

SmartServices/views.py
import email
import imp
from re import U
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string




# Create your views here.
from .models import Order, Partners, Category
from .forms import CreateUserForm, AddPartner, PlaceOrder


# @login_required(login_url='SmartServices:login')
def home(request):
    workers = Partners.objects.all().count()
    Countuser = User.objects.all().count()
    OrderCount = Order.objects.all().count()
    context = {
         'partners': workers,
         'Countuser':Countuser,
         'Ordercount':OrderCount
    }
    return render(request, 'HeaderBase.html',context)

    # return render(request, 'Home.html')


@login_required(login_url='SmartServices:login')
def HirePage(request):
    return render(request, 'MainPages/Categories.html')


def categories(request):
    return {
        'categories': Category.objects.all()
    }

@login_required(login_url='SmartServices:login')
def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    partners = Partners.objects.filter(category=category)
    return render(request, 'MainPages/Hire_Emp.html', {'Category': category, 'partner': partners})

@login_required(login_url='SmartServices:login')
def worker_details(request, slug):
    if request.method == "POST":
        Name = request.POST['name']
        Email = request.POST['email']
        Phone = request.POST['phone']
        Address = request.POST['address']
        Ammount = request.POST['ammount']
        WorkerName = request.POST['workername']

        PlaceOrder = Order(Name = Name, Email = Email, Phone = Phone, Address = Address, Ammount = Ammount, WokerName = WorkerName)
        PlaceOrder.save()
        print(WorkerName)

        return redirect('SmartServices:email')

    worker = get_object_or_404(Partners, slug=slug)
    return render(request, 'MainPages/Single_Detail.html', {'workers': worker})



def BuyPageworker(request, slug):
    worker = get_object_or_404(Partners, slug=slug)
    return render(request, 'MainPages/BuyPage.html', {'workers': worker})

def partnerhome(request):
    return render(request, 'Base.html')


def Aboutus(request):
    return render(request,'PartnerPage/Aboutus.html' )


def Contact(request):
    return render(request,'PartnerPage/Contactus.html' )




# Adding Data into patner model.
def CreatePatner(request):
    if request.method == 'POST':
        form = AddPartner(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('Name')
            messages.success(request, "Welcome To Smart Services  " + user)
         
            return redirect('SmartServices:base')
    else:
        form = AddPartner()
    return render(request, 'MainPages/AddingPartner.html', {'form': form})



## Sending Email 

def SuccesEmail(request):
    import datetime
    NextDay_Date = datetime.datetime.today() + datetime.timedelta(days=2)
    Day = NextDay_Date.day 
    Month = NextDay_Date.month 
    Y = NextDay_Date.year 
       
    tenplate = render_to_string('Email_Pop/EmailTmp.html',{'name':request.user})
    email = EmailMessage(
        ['SMART_SERVICES',Day,Month,Y],
        tenplate,
        settings.EMAIL_HOST_USER,
        [request.user.email],
    )
    email.fail_silently = False
    email.send(NextDay_Date)
    return render(request,'Email_Pop/Pop.html')







def register(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, "Acoount Created " + user)

                return redirect('SmartServices:login')

        context = {'form': form}
        return render(request, 'AccountData/Register.html', context)


def loginpage(request):
    if request.user.is_authenticated:
        return redirect('/')

    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/')

            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'AccountData/Login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('SmartServices:login')

SmartServices/templates/MainPages/AddingPartner.html
<!DOCTYPE html>

<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <!---<title> Responsive Registration Form | CodingLab </title>-->
    <link rel="stylesheet" href="style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: 'Poppins', sans-serif;
    }

    body {
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
        padding: 10px;
        background: linear-gradient(135deg, #380036, #0CBABA);
    }

    .container {
        max-width: 700px;
        width: 100%;
        background-color: #fff;
        padding: 25px 30px;
        border-radius: 5px;
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.15);
    }

    .container .title {
        font-size: 25px;
        font-weight: 500;
        position: relative;
    }


    .container .title::before {
        content: "";
        position: absolute;
        left: 0;
        bottom: 0;
        height: 3px;
        width: 300px;
        border-radius: 5px;
        background: linear-gradient(135deg, #dd33d5, #20dbcc);
    }

    .content form .user-details {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        margin: 20px 0 12px 0;
    }

    form .user-details .input-box {
        margin-bottom: 15px;
        width: calc(100% / 2 - 20px);
    }

    form .input-box span.details {
        display: block;
        font-weight: 500;
        margin-bottom: 5px;
    }

    .user-details .input-box input {
        height: 45px;
        width: 100%;
        outline: none;
        font-size: 16px;
        border-radius: 5px;
        padding-left: 15px;
        border: 1px solid #ccc;
        border-bottom-width: 2px;
        transition: all 0.3s ease;
    }

    .user-details .input-box input:focus,
    .user-details .input-box input:valid {
        border-color: #9b59b6;
    }

    form .gender-details .gender-title {
        font-size: 20px;
        font-weight: 500;
    }

    form .category {
        display: flex;
        width: 80%;
        margin: 14px 0;
        justify-content: space-between;
    }

    form .category label {
        display: flex;
        align-items: center;
        cursor: pointer;
    }

    form .category label .dot {
        height: 18px;
        width: 18px;
        border-radius: 50%;
        margin-right: 10px;
        background: #d9d9d9;
        border: 5px solid transparent;
        transition: all 0.3s ease;
    }

    #dot-1:checked~.category label .one,
    #dot-2:checked~.category label .two,
    #dot-3:checked~.category label .three {
        background: #c48e47;
        border-color: #d9d9d9;
    }

    form input[type="radio"] {
        display: none;
    }

    form .button {
        height: 45px;
        margin: 35px 0
    }

    form .button input {
        height: 100%;
        width: 100%;
        border-radius: 5px;
        border: none;
        color: #fff;
        font-size: 18px;
        font-weight: 500;
        letter-spacing: 1px;
        cursor: pointer;
        transition: all 0.3s ease;
        background: linear-gradient(135deg, #0D324D, #60b9ec);
    }

    form .button input:hover {
        /* transform: scale(0.99); */
        background: linear-gradient(-135deg, #71b7e6, #43c97a);
    }

    .mt-4 a {
        font-size: larger;
        color: black;
    }

    @media(max-width: 584px) {
        .container {
            max-width: 100%;
        }

        form .user-details .input-box {
            margin-bottom: 15px;
            width: 100%;
        }

        form .category {
            width: 100%;
        }

        .content form .user-details {
            max-height: 300px;
            overflow-y: scroll;
        }

        .user-details::-webkit-scrollbar {
            width: 5px;
        }
    }

    @media(max-width: 459px) {
        .container .content .category {
            flex-direction: column;
        }
    }
</style>

<body>
    <div class="container">
        <div class="title">One team – One dream. </div>
        <div class="content">
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="user-details">
                    <div class="input-box">
                        <span class="details">Category</span>
                        {{ form.category}}
                    </div>

                    <div class="input-box">
                        <span class="details">Name</span>
                        {{ form.Name}}
                    </div>
                    <div class="input-box">
                        <span class="details">Address</span>
                        {{ form.Address}}
                    </div>

                    <div class="input-box">
                        <span class="details">Contact</span>
                        {{ form.Contact}}
                    </div>

                    <div class="input-box">
                        <span class="details">Alternate Contact</span>
                        {{ form.Alternate_Contact}}
                    </div>

                    <div class="input-box">
                        <span class="details">Price</span>
                        {{ form.price}}
                    </div>

                    <div class="input-box">
                        <span class="details">Other Expertise</span>
                        {{ form.OtherExpertise}}
                    </div>

                    <div class="input-box">
                        <span class="details">Store Name</span>
                        {{ form.slug}}
                    </div>
                    <br>

                    <div class="input">
                        <br>
                        <span class="details">Image</span>
                        {{ form.image}}

                    </div>

                </div>


                <div class="button">
                    <input type="submit" value="Partner">
                </div>

                <div class="mt-4">
                    <div class="d-flex justify-content-center links">

                        <a href="{% url 'SmartServices:home' %}" class="ml-2">Go Back To Home Page </a>

                    </div>


                    {{form.errors}}
                </div>
            </form>
        </div>
    </div>
    <script>

        /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
    //We start indexing at one because CSRF_token is considered and input field 
    */

        //Query All input fields
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder = 'Name...';
        form_fields[2].placeholder = 'Address...';
        form_fields[3].placeholder = 'Contact No...';
        form_fields[4].placeholder = 'Alternate Contact No...';
        form_fields[5].placeholder = 'Charges/H...';
        form_fields[7].placeholder = 'Indian Plumbing Center';


        for (var field in form_fields) {
            form_fields[field].className += ' form-control'
        }
    </script>

</body>

</html>

SmartServices/templates/MainPages/BuyPage.html
{% extends '../HeaderBase.html' %}
{% load static %}
{%block title%} Worker_Detail {%endblock%}
{% block Main_Content%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    .col-50 {
        -ms-flex: 50%;
        /* IE10 */
        flex: 50%;
    }


    input[type=text] {
        height: 35px;
        width: 65%;
        outline: none;
        font-size: 16px;
        border-radius: 5px;
        padding-left: 15px;
        border: 1px solid #ccc;
        border-bottom-width: 2px;
        transition: all 0.3s ease;
    }

    label {
        display: flex;
        align-items: center;
        cursor: pointer;
        padding: 10px;
    }

    .c3 {
        display: inline-block;
        float: left;
        width: 40%;
        text-align: center;
        padding: 10px 0;
        background-color: #44355b;
        background-image: linear-gradient(315deg, #44355b 0%, #ececec 74%);
        margin: 0px;
        margin-top: 5px;
        margin-left: 21px;

    }

    .c2 {
        display: inline-block;
        float: right;
        width: 40%;
        text-align: center;
        padding: 50px 0;
        background-color: #44355b;
        background-image: linear-gradient(315deg, #44355b 0%, #ececec 74%);
        margin: 0px;
        margin-top: 170px;
        margin-right: 21px;

    }


    @media only screen and (max-width: 660px) {


        .c3 {
            width: 100%;
            margin-top: 40px;
        }

        .c3 {
            width: 100%;
            margin-top: 40px;
        }
    }

    /* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other (and change the direction - make the "cart" column go on top) */
    @media (max-width: 800px) {
        .row {
            flex-direction: column-reverse;
        }

        .col-25 {
            margin-bottom: 120px;
        }
    }
</style>

<body>

    <div class="c3">
        <div class="col-50">
            <h3>Billing Address</h3>
            <label for="fname"><i class="fa fa-user"></i> First Name</label>
            <input type="text" id="fname" name="firstname" value="{{request.user}}">

            <label for="email"><i class="fa fa-envelope"></i> Email</label>
            <input type="text" id="email" name="email"value="{{request.email}}">

            <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
            <input type="text" id="adr" name="address" placeholder="542 W. 15th Street">

            <label for="city"><i class="fa fa-institution"></i> City</label>
            <input type="text" id="city" name="city" placeholder="Sangli">

            <div class="row">
                <div class="col-50">
                    <label for="state">State</label>
                    <input type="text" id="state" name="state" placeholder="Maharashtra">
                </div>
                <div class="col-50">
                    <label for="zip">Zip</label>
                    <input type="text" id="zip" name="zip" placeholder="10101">
                </div>
            </div>
        </div>
    </div>
</body>

</html>
{% endblock %}

SmartServices/templates/MainPages/Categories.html
{% extends '../HeaderBase.html' %}
{% load static %}
{%block title%} Services Page {%endblock%}
{% block Main_Content%}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Responsive Services Section</title>
  <!-- Font Awesome CDN-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
  <!-- Google Font -->
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet" />
  <!-- Stylesheet -->
</head>
<style>
  h1{
    text-align: center;
    text-transform:capitalize;
    color: white;
    font-family:Goudy Old Style;
  }
  .card {
    box-sizing: border-box;
  
    float: left;
    width: calc(25% - 20px);
    padding: 10px;
    border-radius: 20px;
    margin: 10px;
    height: 200px;
    transition: transform 400ms;
    background-color: #7a7adb;
    background-image: linear-gradient(315deg, #ddd6f3 ,#f7bcb9f6 84%);

  }

  .card:hover {
    transform: translateY(-15px);
    background-color: #d2a813;
    background-image: linear-gradient(315deg,#ee9ca7 , #ffdde1 74%);
    cursor: pointer;
  }

  .card h2 {
    font-size: 25px;
    text-align: center;
    margin-top: 80px;

  }

  .card a {
    color: rgb(0, 0, 0);
    text-decoration: none;
    font-family: Perpetua;
  }

  .cardContainer:after {
    content: "";
    display: table;
    clear: both;
  }

  @media screen and (max-width: 600px) {
    .card {
      width: 95%;
    }
  }
</style>


<body>
  <h1> We’re here when you need us most.</h1>
  {% for C in categories %}
  <div class="cardContainer">
    <div class="card">
      <h2><a href="{{ C.get_absolute_url }}"> {{ C.Name|title }} </a></h2>

    </div>
    {% endfor %}
    <!--     
  <section>
   
    <div class="row">
      <h2 class="section-heading">Our Services</h2>
    </div>

    <div class="row">
      {% for C in categories %}
    
      <div class="column">
        
        <div class="card">
          
   
            
          
           
                
          <li>
            <h1><a href="{{ C.get_absolute_url }}"> {{ C.Name|title }} </a></h1>
          </li>
          <!-- Service Heading</h3> -->


    <!-- </div>
        
      </div>
      {% endfor %}
    </div>
  
    </div> -->

    <!-- </section> -->

</body>

</html>
{% endblock %}

SmartServices/templates/MainPages/Demo.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    .register-photo {
        background: #f1f7fc;
        padding: 80px 0
    }

    .register-photo .image-holder {
        display: table-cell;
        width: auto;
        background: url(https://i.imgur.com/Fqm9rWL.jpg);
        background-size: cover
    }

    .register-photo .form-container {
        display: table;
        max-width: 900px;
        width: 90%;
        margin: 0 auto;
        box-shadow: 1px 1px 5px rgba(0, 0, 0, 0.1)
    }

    .register-photo form {
        display: table-cell;
        width: 400px;
        background-color: #ffffff;
        padding: 40px 60px;
        color: #505e6c
    }

    @media (max-width:991px) {
        .register-photo form {
            padding: 40px
        }
    }

    .register-photo form h2 {
        font-size: 24px;
        line-height: 1.5;
        margin-bottom: 30px
    }

    .register-photo form .form-control {
        background: transparent;
        border: none;
        border-bottom: 1px solid #dfe7f1;
        border-radius: 0;
        box-shadow: none;
        outline: none;
        color: inherit;
        text-indent: 0px;
        height: 40px
    }

    .register-photo form .form-check {
        font-size: 13px;
        line-height: 20px
    }

    .register-photo form .btn-primary {
        background: green;
        border: none;
        border-radius: 4px;
        padding: 11px;
        box-shadow: none;
        margin-top: 35px;
        text-shadow: none;
        outline: none !important
    }

    .register-photo form .btn-primary:hover,
    .register-photo form .btn-primary:active {
        background: green
    }

    .register-photo form .btn-primary:active {
        transform: translateY(1px)
    }

    .register-photo form .already {
        display: block;
        text-align: center;
        font-size: 12px;
        color: #6f7a85;
        opacity: 0.9;
        text-decoration: none
    }
</style>

<body>

    <div class="register-photo">
        <div class="form-container">
            <div class="image-holder"></div>
            <form method="post">
                <h2 class="text-center"><strong>Create</strong> an account.</h2>
                <div class="form-group"><input class="form-control" type="email" name="email" placeholder="Email"></div>
                <div class="form-group"><input class="form-control" type="password" name="password"
                        placeholder="Password"></div>
                <div class="form-group"><input class="form-control" type="password" name="password-repeat"
                        placeholder="Password (repeat)"></div>
                <div class="form-group">
                    <div class="form-check"><label class="form-check-label"><input class="form-check-input"
                                type="checkbox">I agree to the license terms.</label></div>
                </div>
                <div class="form-group"><button class="btn btn-success btn-block" type="submit">Sign Up</button></div><a
                    class="already" href="#">You already have an account? Login here.</a>
            </form>
        </div>
    </div>



</body>

</html>

SmartServices/templates/MainPages/Hire_Emp.html
{% extends '../HeaderBase.html' %}
{% load static %}
{%block title%} Hire_Employees {%endblock%}
{% block Main_Content%}
<style>
  .container {
    width: 1500px;
    min-height: 600px;
    display: flex;
    flex-wrap: wrap;
  }

  .content h1{
    color: rgb(255, 255, 255);
    background-color: rgba(23, 173, 111, 0.781);
    height: 40px;
    width: 150px;
    text-align: center;
    padding: 8px;
    font-size: 25px;
  }
  .card {
    position: relative;
    width: calc(50% - 20px);
    min-height: 300px;
    background: #fff;
    margin: 10px;
    box-sizing: border-box;
  }

  .card .imgBx {
    position: absolute;
    width: 50%;
    height: 100%;
  }

  .card .imgBx img {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  .card .details {
    position: absolute;
    right: 0;
    width: 50%;
    height: 100%;
    box-sizing: border-box;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .card .details .content {
    padding: 20px;
    box-sizing: border-box;
  }

  .card .details .content h2 {
    margin: 0;
    padding: 0;
    font-size: 24px;
    line-height: 0.85em;
    font-weight: 600;
  }

  .card .details .content h2 span {
    font-size: 14px;
    color: #777;
  }

  .card .details .content ul {
    margin: 0;
    padding: 0;
    display: flex;
  }

  .card .details .content ul li {
    list-style: none;
    margin-left: 2px;
  }

  .card .details .content ul li a {
    color: #fff;
    border: none;
  }

  .card .details .content ul li:nth-child(1) a {
    background: #3b5995;
  }

  .card .details .content a {
    display: inline-block;
    text-decoration: none;
    padding: 5px 10px;
    margin-top: 10px;
    border: 2px solid #262626;
    color: #262626;
    font-weight: 500;
  }

  .card .details .content a:hover {
    background: #262626;
    color: #fff;
  }

  @media (max-width: 1200px) {
    .container {
      width: 100%;
    }
  }

  @media (max-width: 991px) {
    .card {
      width: calc(70% - 20px);
      margin: 10px auto;
    }
  }

  @media (max-width: 768px) {
    .card {
      width: calc(70% - 20px);
      margin: 10px auto;
    }

    .card .imgBx {
      position: relative;
      width: 100%;
      height: 200px;
    }

    .card .details {
      position: relative;
      width: 100%;
      height: 200px;
    }
  }

  @media (max-width: 480px) {
    .card {
      width: calc(100% - 40px);
      margin: 10px auto;
    }
  }
</style>


<body>

  <div class="container">
   {% for Partners in partner %}
    <div class="card">
      
      <div class="imgBx">
      
        <img src="  {{ Partners.image.url }}" alt="">
      </div>
      <div class="details">
        <div class="content">
          <h2><a href="{{ Partners.get_absolute_url }}">{{ Partners.Name }} <br></a>
            <span>{{ Partners.Address }}</span>
          </h2>
          <ul>
            <li><a href="#"><span>&#8377;</span> {{ Partners.price }} Min/Charges</a></li>
          </ul>
          <a href="#">{{ Partners.Contact }}</a>
           <h1>{{ Partners.category }}</h1>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  
  </div>
  </div>
{% endblock %}  

SmartServices/templates/MainPages/Partner.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Partners</title>
</head>
<body>
   
     {% for partner in partners %}
    {{ partner.Name }}
    {{ partner.price }}

    <img src="{{ partner.image.url }}" alt="Partner Image">
    
    
    {% endfor %}


</body>
</html>