SS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('SmartServices.urls')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

SmartServices/urls.py
from typing import Pattern
from django.contrib import admin
from django.urls import path
from . import views

app_name = "SmartServices"


urlpatterns = [
    path('',views.home,name= "home"),
    path('base/',views.partnerhome,name= "base"),
    path('About/',views.Aboutus,name= "about"),
    path('Contact/',views.Contact,name= "contact"),
 
    path('Email/',views.SuccesEmail,name= "email"),
    path('register/', views.register, name="register"),
    path('login/',views.loginpage, name= "login"),
    path('logout/',views.logoutUser, name= "logout"),

    path('HirePage/',views.HirePage, name= "HirePage"),

    path(r'form/',views.CreatePatner, name= "form"),
    # path(r'form/',views.FinalPlaceOrder, name= "form2"),

    path(r'worker/<slug:slug>/',views.worker_details, name= "worker_details"),

    path('search/<slug:category_slug>/', views.category_list, name= "category_list"),
]

SmartServices/models.py
from datetime import timezone
from email.policy import default
from turtle import mode
from django.db import models
from django.db import models
from django.db.models.expressions import F
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User

class Category(models.Model):
    Name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('SmartServices:category_list', args=[self.slug])

    def __str__(self):
        return self.Name


class Partners(models.Model):
    category = models.ForeignKey(
        Category, related_name='partner', on_delete=models.CASCADE)
    # created_by = models.ForeignKey(
    #     settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='Partner_maker',default='Admin')
    
    Name = models.CharField(max_length=255)
    Address = models.CharField(max_length=255, default='Sangli')
    Contact = models.CharField(max_length=15, null=False, unique=True)
    Alternate_Contact = models.CharField(max_length=15, null=False, unique=True)

    image = models.ImageField(upload_to='images/', default='images/SSDefault.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    OtherExpertise = models.CharField(max_length=255, default="None")

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'partner'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse("SmartServices:worker_details", args=[self.slug])

    def __str__(self):
        return self.Name

class Order(models.Model):
    Name = models.CharField(max_length=250)
    Email = models.EmailField(max_length=255)
    Phone = models.IntegerField()
    Address = models.CharField(max_length=250)                      
    Date = models.DateTimeField(auto_now_add=True)
    Ammount = models.CharField(max_length=100) 
    WokerName = models.CharField(max_length=555)
    
    class Meta:
        verbose_name_plural = 'Order'
    
    def __str__(self):
        return self.Name

SmartServices/forms.py
from django.db.models import fields
from django.db.models.base import Model
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name','last_name' ,'email', 'username','password1', 'password2']

class AddPartner(ModelForm):
    class Meta:
        model = Partners
        fields = '__all__'
        # exclude = ['user']


class PlaceOrder(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        # exclude = ['user']
        

SmartServices/views.py
import email
import imp
from re import U
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string




# Create your views here.
from .models import Order, Partners, Category
from .forms import CreateUserForm, AddPartner, PlaceOrder


# @login_required(login_url='SmartServices:login')
def home(request):
    workers = Partners.objects.all().count()
    Countuser = User.objects.all().count()
    OrderCount = Order.objects.all().count()
    context = {
         'partners': workers,
         'Countuser':Countuser,
         'Ordercount':OrderCount
    }
    return render(request, 'HeaderBase.html',context)

    # return render(request, 'Home.html')


@login_required(login_url='SmartServices:login')
def HirePage(request):
    return render(request, 'MainPages/Categories.html')


def categories(request):
    return {
        'categories': Category.objects.all()
    }

@login_required(login_url='SmartServices:login')
def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    partners = Partners.objects.filter(category=category)
    return render(request, 'MainPages/Hire_Emp.html', {'Category': category, 'partner': partners})

@login_required(login_url='SmartServices:login')
def worker_details(request, slug):
    if request.method == "POST":
        Name = request.POST['name']
        Email = request.POST['email']
        Phone = request.POST['phone']
        Address = request.POST['address']
        Ammount = request.POST['ammount']
        WorkerName = request.POST['workername']

        PlaceOrder = Order(Name = Name, Email = Email, Phone = Phone, Address = Address, Ammount = Ammount, WokerName = WorkerName)
        PlaceOrder.save()
        print(WorkerName)

        return redirect('SmartServices:email')

    worker = get_object_or_404(Partners, slug=slug)
    return render(request, 'MainPages/Single_Detail.html', {'workers': worker})



def BuyPageworker(request, slug):
    worker = get_object_or_404(Partners, slug=slug)
    return render(request, 'MainPages/BuyPage.html', {'workers': worker})

def partnerhome(request):
    return render(request, 'Base.html')


def Aboutus(request):
    return render(request,'PartnerPage/Aboutus.html' )


def Contact(request):
    return render(request,'PartnerPage/Contactus.html' )




# Adding Data into patner model.
def CreatePatner(request):
    if request.method == 'POST':
        form = AddPartner(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('Name')
            messages.success(request, "Welcome To Smart Services  " + user)
         
            return redirect('SmartServices:base')
    else:
        form = AddPartner()
    return render(request, 'MainPages/AddingPartner.html', {'form': form})



## Sending Email 

def SuccesEmail(request):
    import datetime
    NextDay_Date = datetime.datetime.today() + datetime.timedelta(days=2)
    Day = NextDay_Date.day 
    Month = NextDay_Date.month 
    Y = NextDay_Date.year 
       
    tenplate = render_to_string('Email_Pop/EmailTmp.html',{'name':request.user})
    email = EmailMessage(
        ['SMART_SERVICES',Day,Month,Y],
        tenplate,
        settings.EMAIL_HOST_USER,
        [request.user.email],
    )
    email.fail_silently = False
    email.send(NextDay_Date)
    return render(request,'Email_Pop/Pop.html')







def register(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, "Acoount Created " + user)

                return redirect('SmartServices:login')

        context = {'form': form}
        return render(request, 'AccountData/Register.html', context)


def loginpage(request):
    if request.user.is_authenticated:
        return redirect('/')

    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('/')

            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'AccountData/Login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('SmartServices:login')

SmartServices/templates/Base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <title>Partners</title>
</head>
<style>
    * {
        margin: 0;
        padding: 0;
    }

    body {
        font-family: 'Lato', sans-serif;
    }

    .wrapper {
        width: 1170px;
        margin: auto;
    }

    header {
        background: linear-gradient(#42275a, #734b6d);
        height: 100vh;
        -webkit-background-size: cover;
        background-size: cover;
        background-position: center center;
        position: relative;
    }

    .nav-area {
        float: right;
        list-style: none;
        margin-top: 30px;
    }

    .nav-area li {
        display: inline-block;
    }

    .nav-area li a {
        color: #fff;
        text-decoration: none;
        padding: 6px 107px;
        font-family: poppins;
        font-size: 16px;
        text-transform: uppercase;
    }

    .nav-area li a:hover {
        background: #fff;
        color: #333;
    }

    .logo {
        position: relative;
        top: 0;
    }

    .logo img {
        width: 30%;
        position: absolute;
        top: 0px;
    }

    .welcome-text {
        position: absolute;
        width: 600px;
        height: 300px;
        margin: 20% 30%;
        text-align: center;
    }

    .welcome-text h1 {
        text-align: center;
        color: #fff;
        text-transform: uppercase;
        font-size: 60px;
        font-family: serif;
    }

    .welcome-text a {
        border: 1px solid #fff;
        padding: 10px 25px;
        text-decoration: none;
        text-transform: uppercase;
        font-size: 14px;
        margin-top: 20px;
        display: inline-block;
        color: #fff;
    }

    .welcome-text a:hover {
        background: #fff;
        color: #333;
    }

    /*resposive*/

    @media (max-width:600px) {
        .wrapper {
            width: 100%;
        }

        .logo {
            float: none;
            width: 50%;
            text-align: center;
            margin: auto;
        }

        img {
            width: 10%;
        }

        .nav-area {
            float: none;
            margin-top: 0;
        }

        .nav-area li a {
            padding: 5px 15px 7px;
            font-size: 11px;
        }

        .nav-area {
            text-align: center;
        }

        .welcome-text {
            width: 100%;
            height: auto;
            margin: 30% 0;
        }

        .welcome-text h1 {
            font-size: 30px;
        }
    }
</style>

<body>
    <header>
        <div class="wrapper">
            <div class="logo">
                <img src="" alt="">
            </div>
            <ul class="nav-area">
                <li><a href="#">Home</a></li>
                <li><a href="{% url 'SmartServices:HirePage' %}">Services</a></li>
                <li><a href="{% url 'SmartServices:about' %}">ABOUT US</a></li>
                <li><a href="{% url 'SmartServices:contact' %}">CONTACT US</a></li>
            </ul>
        </div>
        <div class="welcome-text">
            <h1>SMART - SERVICES

            </h1>
            <a href=""> {% for message in messages %}
                <p id="messages">{{message}} <br> <br> Yoo! We Are Partner Now </p>
                {% endfor %}
            </a>
         
        </div>
    </header>

</body>

</html>

SmartServices/templates/HeaderBase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'HeaderBase11.css' %}" type="text/css">
    <title>{% block title %}Smart-Services{% endblock %}</title>

</head>

<body>
    <div id="header">
        {% if user.is_authenticated %}
        <div id="logo">
            <h1>SmartServices</h1>
        </div>

        <div id="menu">

            <ul>
                <li> <a href="/">Home</a></li>
                <li> <a href="{% url 'SmartServices:HirePage' %}">Services</a></li>
                <li> <a href="{% url 'SmartServices:form' %}">Partner</a></li>
                <li> <a href="{% url 'SmartServices:logout' %}"> Log_Out</a></li>
                <li>

                    <h4> Hello, {{request.user}}</h4>
                </li>
                {% comment %} {% for message in messages %}
                <p id="messages">{{message}}</p>
                {% endfor %} {% endcomment %}

            </ul>
           

        </div>
     

    </div>


    {% block Main_Content %}

    <div class="row">
        <div class="column">
            <h2>Site Dashboard</h2>
            <hr>
            <br>
            <p> Users = {{ Countuser }}</p>

            <p> Employees = {{ partners }} </p>
            <p> Complete Work = {{ Ordercount }} +</p>

        </div>
        <div class="column">
            <h2> Satisfied Customer Feedback</h2>
            <hr><br>
            <p>Got it. Excellent job! Everything works perfectly! Thanks! </p>
            <h4>Rajesh Shaha</h4>

            <p> Good Site To hire employees, Thanks! </p>
            <h4>Minal Mohite</h4>

            <p> Need More Category & employees options </p>
            <h4>Sumit Kale</h4>

        </div>
    </div>


    {% endblock Main_Content %}


    {% else %}


    <div id="logo">
        <h1>SmartServices</h1>

    </div>

    <div id="menu">

        <ul>
            <li> <a href="/">Home</a></li>
            <li> <a href="{% url 'SmartServices:HirePage' %}">Services</a></li>
            <li> <a href="{% url 'SmartServices:form' %}">Partner</a></li>
            <li> <a href="{% url 'SmartServices:logout' %}"> Log_in</a></li>
            <li>
                <h4> Welcome...</h4>
               
            </li>
          
           
    </div>
  

    <div class="About">
        <h3> Welcome To The Smart-Services </h3>
        <!-- <h3> Smart-Services Works For You.</h3> -->
        <p>
            After the Corona epidemic you see that you have no workers to do your job.
            Even during these illnesses, you have to go out and look for workers every time.But you still don't get any workers.
            If you get a worker, he asks for a lot of money more than that work value.
            <br><br>
            With the help of &nbsp; <span>  Smart-Services  </span>  &nbsp;  you don't have to go out and find employees to do your work.
            We help you find the right staff for your job.
            There is no bargaining system on this site, labor rates are fixed and we are concerned about it.
            We offer you more than 10 services right now.
            We also provide more than 5 employees and their information in each service.
            You have the freedom to choose the particular staff you want for your job.
            The registration and login process is quite simple.
            We offer you one click hire facility you just have to visit our site, find your services and check different
            workers and just click on hire button. And the staff will reach you in the allotted time.

        </p>
    </div>


    {% endif %}

</body>

</html>

SmartServices/templates/Home.html
<!-- <!DOCTYPE html>
<html>

<head>
  <title>Responsive Header</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=1">
</head>
<style>
  body {
    margin: 0px;
    margin-top: 0px;
    background-image: radial-gradient(circle 759px at -6.7% 50%, rgba(80, 131, 73, 1) 0%, rgba(140, 209, 131, 1) 26.2%, rgba(178, 231, 170, 1) 50.6%, rgba(144, 213, 135, 1) 74.1%, rgba(75, 118, 69, 1) 100.3%)
  }

  #header {
    width: 100%;
    float: left;
    text-align: center;
    /* background-image: radial-gradient( circle 759px at -6.7% 50%, rgba(80,131,73,1) 0%, rgba(140,209,131,1) 26.2%, rgba(178,231,170,1) 50.6%, rgba(144,213,135,1) 74.1%, rgba(75,118,69,1) 100.3% ); */
  }

  #logo {
    width: 30%;
    float: left;
  }

  #logo h1 {
    cursor: pointer;
    transition: 1s;
    color: white;
    font-family: cambria;
  }

  #logo h1:hover {
    color: black;
  }

  h4 {
    cursor: pointer;
    transition: 1s;
    color: rgb(255, 255, 255);
    font-family: cambria;
  }




  #menu {
    float: left;
    width: 70%;
  }

  #menu ul {
    margin-right: 10%;
    padding: 0;
    float: right;
    text-align: center;
  }

  #menu ul li {
    cursor: pointer;
    list-style-type: none;
    display: inline-block;
    padding: 8px;
  }

  #menu ul li a {
    font-family: cambria;
    text-decoration: none;
    color: white;
    font-size: 20px;
  }

  #menu ul li a:hover {
    color: black;
  }


  /* Responsive CSS */

  @media only screen and (max-width: 590px) {
    #header {
      font-size: 14px;
    }

    #logo {
      width: 100%;
      float: left;
      text-align: center;
    }

    #menu {
      width: 100%;
      margin: 0 auto;
    }

    #menu ul {
      float: none;
      margin-right: 0px;
    }
  }

  @media only screen and (max-width: 320px) {
    #header {
      font-size: 12px;
    }

    #logo h1 {
      margin-bottom: 1%;

    }

    #menu ul li {
      display: block;
    }
  }








  /* Middle Content */



  .c2 {
    display: inline-block;
    float: left;
    width: 50%;
    text-align: center;
    padding: 180px 0;
    margin: 0px;
    /* background-color #55efc4; */
    background-image: linear-gradient(315deg,#FFFEFF , #D7FFFE
);
    margin-top: 80px;
    margin-left: 5px;


  }

  .c3 {
    display: inline-block;
    float: left;
    width: 49%;
    text-align: center;
    padding: 180px 0;
    background-color: #44355b;
    background-image: linear-gradient(315deg, #44355b 0%, #ececec 74%);
    margin: 0px;
    margin-top: 80px;
    margin-left: 2px;

  }



  @media only screen and (max-width: 660px) {
    .c2 {
      width: 100%;
    }

    .c3 {
      width: 100%;
      margin-top: 40px;
    }
  }

</style>

<body>
  <div id="header">
    {% if user.is_authenticated %}
    <div id="logo">
      <h1>SmartServices</h1>
    </div>
    
    <div id="menu">
     
      <ul>
        <li> <a href="/try/">Home</a></li>
        <li> <a href="{% url 'SmartServices:HirePage' %}">Services</a></li>
        <li> <a href="{% url 'SmartServices:form' %}">Partner</a></li>
        <li> <a href="{% url 'SmartServices:logout' %}"> Log_Out</a></li>
        <li>

          <h4> Hello, {{request.user}}</h4>
        </li>
        {% for message in messages %}
        <p id="messages">{{message}}</p>
        {% endfor %}

      </ul>
     
    </div>
    
  </div>
  {% endif %}



   Middle Content -->
<!-- 
  <div class="2col">
    <div class="c2">Content Area 2</div>
    <div class="c3">Content Area 3</div>
  </div>





   Footer Desing -->


<!-- </body>

</html>  -->

SmartServices/templates/message.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}